cts.directory: /home/guevenira/Data/shared/PDAC_CT/CTs

cst.label.csv: /home/guevenira/Data/shared/PDAC_CT/pseudonymised_patient_info.csv
cts.label.problematic: /home/guevenira/Data/shared/Problematic_CTs

radimagenet.directory: /home/guevenira/Data/shared/radiology_ai/CT/abd


#data.label.name: Radimagenet
#data.label.name.version: radimagenet_v1    # onehot encoded
#data.label.name.version: radimagenet_v2     # class index 

########################################################################

# 80% train, 10% validation, 10% test
#data.label.name: Geschlecht
#data.label.name.version: geschlecht_v1

# DONT FORGET
#'Crop-Height' : {'begin': 0, 'end': 256}
#'Crop-Width' : {'begin': 0, 'end': 256}
#'Max-Layers' : {'max': 200}

########################################################################

data.label.name: Befund-Verlauf
# 80% train, 10% validation, 10% test
#data.label.name.version: befund_verlauf_v1

# 80% train, 10% validation, 10% test
#data.label.name.version: befund_verlauf_v2

# 75% train, 10% validation, 15% test
data.label.name.version: befund_verlauf_v3

# IF RESNET 152 DONT FORGET
#'Crop-Height' : {'begin': 16, 'end': 240}
#'Crop-Width' : {'begin': 16, 'end': 240}
#'Max-Layers' : {'max': 110}

########################################################################

#data.label.name: Befund-Verlauf-Therapie-Procedere
#data.label.name.version: befund_verlauf_therapie_procedere_v1


data.label.balanced: False
data.label.balanced.shuffled: False

data.augmentation: False
data.augmentation.clip_threshold: 1
data.augmentation.horizontal_flip_threshold: 1
data.augmentation.vertical_flip_threshold: 1
data.augmentation.translation_threshold: 0.8
data.augmentation.shear_threshold: 1
data.augmentation.rotation_threshold: 1
data.augmentation.gaussian_blur_threshold: 1                    # this is gaussian blur
data.augmentation.gaussian_threshold: 1                         # this is gaussian noise
data.augmentation.brightness_contrast_sharpness_threshold: 1